version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      target: runner
    command: []
    restart: always
    volumes: []

  postgres:
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

  redis:
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
