import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        chart: {
          "1": "var(--chart-1)",
          "2": "var(--chart-2)",
          "3": "var(--chart-3)",
          "4": "var(--chart-4)",
          "5": "var(--chart-5)",
        },
        sidebar: {
          DEFAULT: "var(--sidebar)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
        },
        // Dynamic variable-backed visual assets
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "on-error-container": "var(--on-error-container)",
        "secondary-container": "var(--secondary-container)",
        "on-tertiary": "var(--on-tertiary)",
        "on-primary": "var(--on-primary)",
        "pg-background": "var(--background)",
        "on-secondary": "var(--on-secondary)",
        "surface-container": "var(--surface-container)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "inverse-primary": "var(--inverse-primary)",
        "outline": "var(--outline)",
        "surface-container-high": "var(--surface-container-high)",
        "on-primary-container": "var(--on-primary-container)",
        "surface": "var(--background)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "tertiary": "var(--tertiary)",
        "on-background": "var(--foreground)",
        "secondary-fixed": "var(--secondary-fixed)",
        "on-surface-variant": "var(--on-surface-variant)",
        "outline-variant": "var(--outline-variant)",
        "surface-tint": "var(--primary)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "surface-container-low": "var(--surface-container-low)",
        "primary-fixed": "var(--primary-fixed)",
        "on-error": "var(--on-error)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "primary-container": "var(--primary-container)",
        "error-container": "var(--error-container)",
        "surface-container-highest": "var(--surface-container-highest)",
        "on-surface": "var(--on-surface)",
        "tertiary-container": "var(--tertiary-container)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "surface-variant": "var(--surface-variant)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "secondary-color": "var(--secondary)",
        "inverse-surface": "var(--inverse-surface)",
        "surface-dim": "var(--background)",
        "error-color": "var(--error)",
        "error": "var(--error)",
        "on-secondary-container": "var(--on-secondary-container)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "surface-bright": "var(--surface-bright)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      spacing: {
        unit: "4px",
        "margin-mobile": "16px",
        "margin-desktop": "24px",
        "container-max": "1440px",
        gutter: "16px",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "sans-serif"],
        mono: ["var(--font-mono)", "monospace"],
        "headline-lg-mobile": ["var(--font-sans)", "sans-serif"],
        "label-md": ["var(--font-mono)", "monospace"],
        "label-sm": ["var(--font-mono)", "monospace"],
        "headline-md": ["var(--font-sans)", "sans-serif"],
        "headline-lg": ["var(--font-sans)", "sans-serif"],
        "body-md": ["var(--font-sans)", "sans-serif"],
        "body-lg": ["var(--font-sans)", "sans-serif"],
        "headline-sm": ["var(--font-sans)", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-sm": ["10px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "1.4", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
export default config;
