import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        chart: {
          "1": "var(--chart-1)",
          "2": "var(--chart-2)",
          "3": "var(--chart-3)",
          "4": "var(--chart-4)",
          "5": "var(--chart-5)",
        },
        sidebar: {
          DEFAULT: "var(--sidebar)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
        },
        // Premium mockup color additions
        "on-tertiary-fixed-variant": "#004f58",
        "tertiary-fixed-dim": "#00daf3",
        "on-error-container": "#ffdad6",
        "secondary-container": "#46494e",
        "on-tertiary": "#00363d",
        "on-primary": "#00391f",
        "pg-background": "#051424",
        "on-secondary": "#2e3135",
        "surface-container": "#122131",
        "tertiary-fixed": "#9cf0ff",
        "inverse-primary": "#006d40",
        "outline": "#849587",
        "surface-container-high": "#1c2b3c",
        "on-primary-container": "#007142",
        "surface": "#051424",
        "on-primary-fixed": "#002110",
        "tertiary": "#f6fdff",
        "on-background": "#d4e4fa",
        "secondary-fixed": "#e1e2e8",
        "on-surface-variant": "#b9cbbc",
        "outline-variant": "#3b4b3f",
        "surface-tint": "#00e38a",
        "on-tertiary-container": "#006d7a",
        "surface-container-low": "#0d1c2d",
        "primary-fixed": "#56ffa7",
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#44474b",
        "primary-container": "#00ff9c",
        "error-container": "#93000a",
        "surface-container-highest": "#273647",
        "on-surface": "#d4e4fa",
        "tertiary-container": "#8eeeff",
        "primary-fixed-dim": "#00e38a",
        "on-secondary-fixed": "#191c20",
        "surface-variant": "#273647",
        "surface-container-lowest": "#010f1f",
        "on-tertiary-fixed": "#001f24",
        "on-primary-fixed-variant": "#00522f",
        "secondary-color": "#c5c6cc",
        "inverse-surface": "#d4e4fa",
        "surface-dim": "#051424",
        "error-color": "#ffb4ab",
        "on-secondary-container": "#b6b8be",
        "secondary-fixed-dim": "#c5c6cc",
        "inverse-on-surface": "#233143",
        "surface-bright": "#2c3a4c"
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      spacing: {
        unit: "4px",
        "margin-mobile": "16px",
        "margin-desktop": "24px",
        "container-max": "1440px",
        gutter: "16px",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "sans-serif"],
        mono: ["var(--font-mono)", "monospace"],
        "headline-lg-mobile": ["var(--font-sans)", "sans-serif"],
        "label-md": ["var(--font-mono)", "monospace"],
        "label-sm": ["var(--font-mono)", "monospace"],
        "headline-md": ["var(--font-sans)", "sans-serif"],
        "headline-lg": ["var(--font-sans)", "sans-serif"],
        "body-md": ["var(--font-sans)", "sans-serif"],
        "body-lg": ["var(--font-sans)", "sans-serif"],
        "headline-sm": ["var(--font-sans)", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-sm": ["10px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "1.4", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
export default config;
